# NumPy Practice Session

Quick one-line recaps only — the focus here is practice. For each topic, solve the questions in the empty code cells provided.


## 1. Array Creation Basics

_`np.array(list)` → from list | `np.zeros(shape)` → all 0s | `np.ones(shape)` → all 1s | `np.full(shape, val)` → custom value | `np.arange(start,stop,step)` → like range()_


**Q1.1** Create a 1D array of 6 numbers of your choice.

In [2]:
import numpy as np

array_1d = np.array([3, 7, 11, 15, 19, 23])
print(array_1d)


[ 3  7 11 15 19 23]


**Q1.2** Create a 3x3 array of zeros and a 2x2 array filled with the value 7.

In [3]:
zeros_3x3 = np.zeros((3, 3), dtype=int)
filled_2x2 = np.full((2, 2), 7)

print("3x3 zeros:\n", zeros_3x3)
print("2x2 filled with 7:\n", filled_2x2)


3x3 zeros:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
2x2 filled with 7:
 [[7 7]
 [7 7]]


**Q1.3** Create an array of odd numbers from 1 to 21 using `arange`.

In [4]:
odd_numbers = np.arange(1, 22, 2)
print(odd_numbers)


[ 1  3  5  7  9 11 13 15 17 19 21]


## 2. Advanced Creation

_`.reshape(r,c)` → change shape | `np.linspace(start,stop,num)` → num evenly spaced values | `np.eye(n)` → n×n identity matrix_


**Q2.1** Create numbers 0 to 11 using `arange` and reshape into a 3x4 matrix.

In [5]:
matrix_3x4 = np.arange(12).reshape(3, 4)
print(matrix_3x4)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q2.2** Generate 7 evenly spaced values between 10 and 50 using `linspace`.

In [6]:
evenly_spaced = np.linspace(10, 50, 7)
print(evenly_spaced)


[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


**Q2.3** Create a 5x5 identity matrix.

In [7]:
identity_5x5 = np.eye(5, dtype=int)
print(identity_5x5)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## 3. Array Attributes

_`.shape` → dimensions tuple | `.ndim` → no. of dimensions | `.size` → total elements | `.dtype` → data type_


**Q3.1** Create a (4,3) array and print its shape, ndim, size, and dtype.

In [8]:
attributes_array = np.arange(12).reshape(4, 3)

print("Shape:", attributes_array.shape)
print("Dimensions:", attributes_array.ndim)
print("Size:", attributes_array.size)
print("Data type:", attributes_array.dtype)


Shape: (4, 3)
Dimensions: 2
Size: 12
Data type: int64


**Q3.2** Create a (3,) vector and check if it's compatible for a dot product with a (5,3) matrix.

In [9]:
vector = np.array([1, 2, 3])
matrix_5x3 = np.arange(15).reshape(5, 3)

is_compatible = vector.shape[0] == matrix_5x3.shape[1]
print("Compatible for matrix @ vector:", is_compatible)
if is_compatible:
    print(matrix_5x3 @ vector)


Compatible for matrix @ vector: True
[ 8 26 44 62 80]


## 4. Indexing & Slicing

_`arr[i]` / `arr[r,c]` → access | `arr[a:b, c:d]` → sub-matrix | `arr[::step]` → step slicing | `arr[::-1]` → reverse_


**Q4.1** Create a 4x4 array with values 1-16. Extract row 2, column 3.

In [10]:
array_4x4 = np.arange(1, 17).reshape(4, 4)
second_row = array_4x4[1, :]
third_column = array_4x4[:, 2]

print("Row 2:", second_row)
print("Column 3:", third_column)


Row 2: [5 6 7 8]
Column 3: [ 3  7 11 15]


**Q4.2** From the same array, extract the sub-matrix of the first two rows and last two columns.

In [11]:
sub_matrix = array_4x4[:2, -2:]
print(sub_matrix)


[[3 4]
 [7 8]]


**Q4.3** Reverse the array row-wise, then column-wise.

In [12]:
reversed_rows = array_4x4[::-1, :]
reversed_columns = array_4x4[:, ::-1]

print("Row-wise reverse:\n", reversed_rows)
print("Column-wise reverse:\n", reversed_columns)


Row-wise reverse:
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Column-wise reverse:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


**Q4.4** Print every 3rd element of a 1-20 array.

In [13]:
one_to_twenty = np.arange(1, 21)
every_third = one_to_twenty[2::3]
print(every_third)


[ 3  6  9 12 15 18]


## 5. Data Types & Coercion

_Mixed types auto-upcast to one common dtype | `.astype(type)` → explicit conversion_


**Q5.1** Create an array mixing ints and floats — check the resulting dtype.

In [14]:
mixed_array = np.array([1, 2.5, 3, 4.75])
print(mixed_array)
print("Data type:", mixed_array.dtype)


[1.   2.5  3.   4.75]
Data type: float64


**Q5.2** Convert a float array [1.9, 2.5, 3.1] to integers using astype.

In [15]:
float_array = np.array([1.9, 2.5, 3.1])
integer_array = float_array.astype(int)
print(integer_array)


[1 2 3]


## 6. Vectorized Arithmetic & Boolean Masking

_`a + b`, `a * b`, `a ** 2` → element-wise ops | `arr[arr > x]` → boolean filtering_


**Q6.1** Create two same-size arrays and compute their sum, product, and squares.

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("Sum:", a + b)
print("Product:", a * b)
print("Squares of a:", a ** 2)
print("Squares of b:", b ** 2)


Sum: [ 6  8 10 12]
Product: [ 5 12 21 32]
Squares of a: [ 1  4  9 16]
Squares of b: [25 36 49 64]


**Q6.2** Create an array of 10 random-looking numbers of your choice, then filter out only values greater than 15 using a boolean mask.

In [17]:
numbers = np.array([3, 18, 9, 27, 15, 22, 4, 31, 12, 19])
mask = numbers > 15
filtered_numbers = numbers[mask]

print("Values greater than 15:", filtered_numbers)


Values greater than 15: [18 27 22 31 19]


## 7. Random Module

_`np.random.seed(n)` → reproducibility | `.rand()` → uniform | `.randn()` → normal | `.randint(low,high,size)` → random ints | `.choice(arr,size)` → random sample | `.shuffle(arr)` → shuffle in place_


**Q7.1** Set a seed, generate a 3x3 uniform random array, and confirm reproducibility by rerunning with the same seed.

In [18]:
np.random.seed(42)
first_random_array = np.random.rand(3, 3)

np.random.seed(42)
second_random_array = np.random.rand(3, 3)

print(first_random_array)
print("Reproducible:", np.array_equal(first_random_array, second_random_array))


[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
Reproducible: True


**Q7.2** Generate 5 values from a normal distribution and 5 random integers between 1-100.

In [19]:
normal_values = np.random.randn(5)
random_integers = np.random.randint(1, 101, size=5)

print("Normal values:", normal_values)
print("Random integers:", random_integers)


Normal values: [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]
Random integers: [49 91 59 42 92]


**Q7.3** Randomly pick 3 values (no repeats) from a list of 8 items, then shuffle a 1-10 array.

In [20]:
items = np.array([1,2,3,4,5,6,7,8,9,10])
picked_items = np.random.choice(items, size=3, replace=False)

one_to_ten = np.arange(1, 11)
np.random.shuffle(one_to_ten)

print("Picked items:", picked_items)
print("Shuffled array:", one_to_ten)


Picked items: [2 9 8]
Shuffled array: [ 6  3  5  8 10  1  4  2  7  9]


## 8. Reduction & Axis Rules

_`.sum()` / `.mean()` / `np.median()` → aggregations | `axis=0` → column-wise | `axis=1` → row-wise_


**Q8.1** Create a 3x3 matrix. Find the total sum, sum along axis=0, sum along axis=1.

In [21]:
reduction_matrix = np.arange(1, 10).reshape(3, 3)

print(reduction_matrix)
print("Total sum:", reduction_matrix.sum())
print("Column sums (axis=0):", reduction_matrix.sum(axis=0))
print("Row sums (axis=1):", reduction_matrix.sum(axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total sum: 45
Column sums (axis=0): [12 15 18]
Row sums (axis=1): [ 6 15 24]


**Q8.2** Find the mean and median of the same matrix.

In [22]:
print("Mean:", reduction_matrix.mean())
print("Median:", np.median(reduction_matrix))


Mean: 5.0
Median: 5.0


## 9. Broadcasting

_Shapes match if equal or one of them is 1 (compared right to left) | smaller array auto-expands to fit_


**Q9.1** Add a (3,3) ones matrix with a 1D array of length 3 — observe the broadcast.

In [23]:
ones_matrix = np.ones((3, 3), dtype=int)
vector = np.array([10, 20, 30])
broadcast_sum = ones_matrix + vector

print(broadcast_sum)


[[11 21 31]
 [11 21 31]
 [11 21 31]]


**Q9.2** Create a row vector (1,3) and column vector (3,1), add them, and check the resulting shape.

In [24]:
row_vector = np.array([[1, 2, 3]])
column_vector = np.array([[10], [20], [30]])
result = row_vector + column_vector

print(result)
print("Result shape:", result.shape)


[[11 12 13]
 [21 22 23]
 [31 32 33]]
Result shape: (3, 3)


## 10. Reshaping & Dimension Expansion

_`reshape(-1, n)` → auto-calculate the other dimension | `arr[np.newaxis, :]` → row vector | `arr[:, np.newaxis]` → column vector_


**Q10.1** Create a 12-element array and reshape it using -1 so it has 4 columns.

In [25]:
array_12 = np.arange(1, 13)
reshaped_array = array_12.reshape(-1, 4)

print(reshaped_array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Q10.2** Take a 3-element 1D array and convert it into a row vector and a column vector using np.newaxis.

In [27]:
vector_1d = np.array([1, 2, 3])
row_vector = vector_1d[np.newaxis, :]
column_vector = vector_1d[:, np.newaxis]

print("Row vector:", row_vector)
print("Column vector:", column_vector)


Row vector: [[1 2 3]]
Column vector: [[1]
 [2]
 [3]]


## 11. Flatten vs Ravel

_`.flatten()` → returns a copy (original safe) | `.ravel()` → returns a view (original can change too)_


**Q11.1** Create a 2D array, flatten it with both methods, modify the first element of each result, and check which one affects the original array.

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

flattened = array_2d.flatten()  # Creates a copy
flattened[0] = 99
print("After modifying flatten():", array_2d)

raveled = array_2d.ravel()  # Creates a view when possible
raveled[0] = 100
print("After modifying ravel():", array_2d)


After modifying flatten(): [[1 2 3]
 [4 5 6]]
After modifying ravel(): [[100   2   3]
 [  4   5   6]]


## 12. Stacking & Concatenation

_`np.vstack()` → stack rows | `np.hstack()` → stack columns | `np.concatenate(axis=)` → general version_


**Q12.1** Create two 2x2 arrays. Combine them using vstack, hstack, and concatenate on both axis=0 and axis=1.

In [30]:
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6], [7, 8]])

print("vstack:", np.vstack((array_a, array_b)))
print("hstack:", np.hstack((array_a, array_b)))
print("concatenate(axis=0):", np.concatenate((array_a, array_b), axis=0))
print("concatenate(axis=1):", np.concatenate((array_a, array_b), axis=1))


vstack: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack: [[1 2 5 6]
 [3 4 7 8]]
concatenate(axis=0): [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate(axis=1): [[1 2 5 6]
 [3 4 7 8]]


## 13. np.where — Conditional Logic

_`np.where(cond, a, b)` → element-wise if/else | `np.where(cond)` → returns matching indices_


**Q13.1** Create a 6-element array. Label each value 'High' or 'Low' based on a threshold using np.where.

In [ ]:
# Write your code here


**Q13.2** Use np.where (without true/false args) to find the indices of values above that threshold.

In [ ]:
# Write your code here


## 14. Matrix Operations & Transpose

_`*` → element-wise multiply | `@` / `np.dot()` → matrix multiplication | `.T` → transpose (rows ↔ cols)_


**Q14.1** Create two 2x2 matrices. Compute their element-wise product and their matrix product (using both @ and np.dot).

In [ ]:
# Write your code here


**Q14.2** Print the transpose of the first matrix.

In [ ]:
# Write your code here


---
## CRUD Operations on Arrays

_Create, Read, Update, Delete/Insert — arrays are fixed-size, so delete/insert return a new array rather than modifying in place._


## 15. CRUD — Create & Read

_Create = `np.array()`/creation helpers | Read = indexing & slicing_


**Q15.1** Create a 1D array of 8 integers and a 2D array of shape (3,3).

In [ ]:
# Write your code here


**Q15.2** Read the element at index 3 from the 1D array, and the middle row from the 2D array.

In [ ]:
# Write your code here


## 16. CRUD — Update

_`arr[i] = val` or `arr[slice] = val` → updates values directly (arrays are mutable)_


**Q16.1** Update index 2 of your 1D array to 100.

In [ ]:
# Write your code here


**Q16.2** Update the entire second row of your 2D array to [0, 0, 0].

In [ ]:
# Write your code here


## 17. CRUD — Delete & Insert

_`np.delete(arr, idx, axis=)` → remove & return new array | `np.insert(arr, idx, val)` → insert value | `np.append(arr, val)` → add at the end_


**Q17.1** Delete the element at index 0 from your 1D array (store as a new variable).

In [ ]:
# Write your code here


**Q17.2** Delete the last column from your 2D array.

In [ ]:
# Write your code here


**Q17.3** Use np.append to add 99 to the end of your 1D array, and np.insert to insert 50 at index 1.

In [ ]:
# Write your code here


## 18. Combined Practice

_No new functions — just combining what's covered above_


**Q18.1** Create a 5x5 array (1-25), extract its center 3x3 block, then find the row-wise sum of that block.

In [ ]:
# Write your code here


**Q18.2** Create two 1D int arrays, stack them with vstack, add 0.5 to the result and check the dtype coercion.

In [ ]:
# Write your code here


**Q18.3** Create a 4x4 matrix with np.diag() using diagonal values 2,4,6,8, then find its transpose.

In [ ]:
# Write your code here
