In [2]:
import numpy as np

In [12]:
arr1=np.arange(10)
print(arr1)
arr1=arr1+10
print(arr1)
print("multi",arr1**5)
arr2=np.arange(30+2)
arr3=np.arange(30+2)
print(arr2+arr3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
multi [ 100000  161051  248832  371293  537824  759375 1048576 1419857 1889568
 2476099]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62]


In [29]:
x=np.arange(10).reshape(5,2)
y=np.arange(10,20).reshape(5,2)
print(x**y)
print(x<y)
print(x>y)
print(x/y)
print(x-y)

[[                  0                   1]
 [               4096             1594323]
 [          268435456         30517578125]
 [      2821109907456     232630513987207]
 [  18014398509481984 1350851717672992089]]
[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]
[[0.         0.09090909]
 [0.16666667 0.23076923]
 [0.28571429 0.33333333]
 [0.375      0.41176471]
 [0.44444444 0.47368421]]
[[-10 -10]
 [-10 -10]
 [-10 -10]
 [-10 -10]
 [-10 -10]]


In [52]:
print(np.random.randn(10))
print(np.random.rand(10))
print(np.random.seed(90))


[-0.50659356 -0.19070639  2.15505312  0.56687955 -0.59535819 -0.32034219
 -1.11874795  0.18605539 -0.45494092 -0.43391861]
[0.5487357  0.5972377  0.9901698  0.93226084 0.41599946 0.16234383
 0.48876738 0.18808813 0.6738954  0.89856542]
None


In [73]:
print(np.random.randint(9,100,size=(2,3)))
print(np.random.randint(9,100,10))


[[15 70 98]
 [16 79 64]]
[53 74 35 97 50 34 84 60 49 75]


In [88]:
lst=[3,4,5,6,7,8,32,4,6,4563,356,5,563,65,35,65,4563,65,3]
print(np.random.choice(lst,2))
print(np.random.choice(3,9))
print(np.random.choice(lst,2,replace=False))
print(np.random.choice(10,5))
ro=np.arange(20)
np.random.shuffle(ro)
print(ro)

[ 6 65]
[2 2 2 1 0 1 1 0 2]
[ 4 65]
[3 4 2 4 9]
[13 11  4 15  5  8  1 19  7 10 12 18  3 17  0 14  6  9  2 16]


In [95]:
np.random.seed(42)
print(np.random.randint(1,7,10))


[4 5 3 5 5 2 3 3 3 5]


In [ ]:
r=np.arange(12).reshape(3,4)



Statistics

In [108]:
st=np.arange(1,11).reshape(5,2)
print(st)
print(st.min())
print("row min",st.min(axis=1))
print("col min",st.min(axis=0))
print("total",st.sum())
print("total",st.sum(axis=1))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
1
row min [1 3 5 7 9]
col min [1 2]
total 55
total [ 3  7 11 15 19]
