In [1]:
import numpy as np

***creating array***

In [7]:
x=np.array([1,2,3,4,5,6])
print(x,type(x))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


In [15]:
y=np.array([[1,2,3],[8,9,0],[0,0,0]])
print(y,type(y))

[[1 2 3]
 [8 9 0]
 [0 0 0]] <class 'numpy.ndarray'>


In [22]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [30]:
print(np.full((3,4), 3))

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [35]:
print(np.arange(1,11).reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
print(np.eye(5,10))
print(np.eye(5,10,k=3))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [40]:
a=np.arange(20).reshape(4,5)
print(a)
print(a.size)
print(a.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
20
int64


In [41]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
arr1=np.ones((3,3))
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
arr2=np.arange(2,21,2)
print(arr2)

[ 2  4  6  8 10 12 14 16 18 20]


In [45]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr3=np.eye(4,4)
print(arr3)
print(len(arr3))
print((arr3))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
4


In [18]:
s=np.arange(0,20).reshape(5,4)
print(s)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [26]:
print(s[::4, ::3])
print(s[1:2,1:4])

[[ 0  3]
 [16 19]]
[[5 6 7]]


In [65]:
print(s[1:3,2::-1])

[[ 6  5  4]
 [10  9  8]]


In [3]:
print(np.array([1,2.3,5,'ankit']))

['1' '2.3' '5' 'ankit']


In [11]:
print(type(9594.234))
x=np.array([1,2,3,4,5,6,6.4,45.4,35],dtype='int32')
print(x)

<class 'float'>
[ 1  2  3  4  5  6  6 45 35]
