In [65]:
import pandas as pd
import numpy as np


In [66]:
restaurant_data={
    "Table_number":[1,2,3,4,5],
    "Bill_amount":[100,200,150,300,250],
    "Waiter_name":["John","Alice","Bob","Eve","Charlie"],
}

In [67]:
df=pd.DataFrame(restaurant_data)
print(df)

   Table_number  Bill_amount Waiter_name
0             1          100        John
1             2          200       Alice
2             3          150         Bob
3             4          300         Eve
4             5          250     Charlie


In [68]:
print(df["Waiter_name"])
print(df["Bill_amount"])


0       John
1      Alice
2        Bob
3        Eve
4    Charlie
Name: Waiter_name, dtype: object
0    100
1    200
2    150
3    300
4    250
Name: Bill_amount, dtype: int64


In [69]:
total_bill=[600,5246,2345,24,5243,4533,5342,45,2]
s=pd.Series("total_bill")
print(s)

0    total_bill
dtype: object


In [70]:
print(df.values)

[[1 100 'John']
 [2 200 'Alice']
 [3 150 'Bob']
 [4 300 'Eve']
 [5 250 'Charlie']]


In [71]:
stocks={
    "brand":["nike","tata","oneoone","google"],
    "price":[1000,10000,1100000,1000000],
    "in_stock":["true","true","true","false"]
}

sd=pd.DataFrame(stocks)
print(sd)

     brand    price in_stock
0     nike     1000     true
1     tata    10000     true
2  oneoone  1100000     true
3   google  1000000    false


In [72]:
df=pd.read_csv("/Users/ankit/BOX 1/B1 ROOM 1/AI&ML/class5/tips.csv")
print(df)
print(df.tail())
print(df.sum())


     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]
     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243    

In [73]:
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size
86,13.03,2.00,Male,No,Thur,Lunch,2
227,20.45,3.00,Male,No,Sat,Dinner,4
133,12.26,2.00,Female,No,Thur,Lunch,2
239,29.03,5.92,Male,No,Sat,Dinner,3
228,13.28,2.72,Male,No,Sat,Dinner,2


In [74]:
df.shape

(244, 7)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [76]:
df.describe()

,total_bill,tip,size
count,244.000000,244.000000,244.000000
mean,19.785943,2.998279,2.569672
std,8.902412,1.383638,0.951100
min,3.070000,1.000000,1.000000
25%,13.347500,2.000000,2.000000
50%,17.795000,2.900000,2.000000
75%,24.127500,3.562500,3.000000
max,50.810000,10.000000,6.000000


In [77]:
print(df.applymap)

<bound method DataFrame.applymap of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>


In [78]:
print(df.flags)
print(df.tip)
print(df.agg)

<Flags(allows_duplicate_labels=True)>
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
<bound method DataFrame.aggregate of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>


In [79]:
x=df['day']
print(x.shape)

y=df[['day']]
print(y.shape)

(244,)
(244, 1)


In [80]:
print(df['day'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 244 entries, 0 to 243
Series name: day
Non-Null Count  Dtype 
--------------  ----- 
244 non-null    object
dtypes: object(1)
memory usage: 2.0+ KB
None


In [81]:
print(df['day'])

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: object


In [82]:
gg=pd.read_csv("/Users/ankit/BOX 1/B1 ROOM 1/AI&ML/Class6/test.csv")
print(gg)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0 

In [83]:
gg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB


In [84]:
gg.shape

(418, 11)

In [85]:
gg.sample()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
56,948,3,"Cor, Mr. Bartol",male,35.0,0,0,349230,7.8958,NaN,S


In [86]:
gg.head(9)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C


In [87]:
marks=np.array([[45,24,56,23,67],
                [78,56,85,85,46],
                [47,97,98,68,56],
                [36,87,56,87,67],
                [56,76,56,75,46]])

print(marks)

[[45 24 56 23 67]
 [78 56 85 85 46]
 [47 97 98 68 56]
 [36 87 56 87 67]
 [56 76 56 75 46]]


In [88]:
gg.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S


In [89]:
gg[["Age"]]

,Age
0,34.5
1,47.0
2,62.0
3,27.0
4,22.0
...,...
413,NaN
414,39.0
415,38.5
416,NaN


In [90]:
gg.iloc[1:4,[1,2,3]]

,Pclass,Name,Sex
1,3,"Wilkes, Mrs. James (Ellen Needs)",female
2,2,"Myles, Mr. Thomas Francis",male
3,3,"Wirz, Mr. Albert",male


In [91]:
gg.loc[1:4,"Name":"Cabin"]

,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin
1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN
2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN
3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN
4,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN


In [92]:
gg.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S


In [100]:
gg[gg["Age"]>65][["Name","Pclass","Fare"]]

,Name,Pclass,Fare
81,"Straus, Mr. Isidor",1,221.7792
96,"Cavendish, Mrs. Tyrell William (Julia Florence...",1,78.8500


In [109]:
gg[(gg["Age"]<10 )| (gg["Age"]>70)]


,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.1708,NaN,S
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.2458,NaN,C
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.0000,NaN,S
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.8500,C46,S
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.7000,G6,S
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.2458,NaN,C
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.5000,NaN,S
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.5000,E34,C
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.4000,NaN,S
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.0000,NaN,S
