In [1]:
import numpy as np

In [4]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
arr1=np.arange(1,5)
print(arr1)
print(arr1+arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]


In [8]:
row=np.arange(3,7)
print(row)
col=np.arange(3,7).reshape(4,1)
print(col)

print(col+row)

[3 4 5 6]
[[3]
 [4]
 [5]
 [6]]
[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]


In [16]:
arr3=np.arange(1,41).reshape(5,-1)
print(arr3,arr3.shape)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]] (5, 8)


In [21]:
arr=np.arange(1,13)
arr1=arr.reshape(1,-1)
arr2=arr.reshape(-1,1)
print("row",arr1)
print("col",arr2)


row [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
col [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [27]:
arr=np.arange(1,13).reshape(4,3)
print(arr)
arr1=arr.ravel()#shellow copy 
print(arr1)
arr1[2]=100
print(arr1)
arr2=arr.flatten()#deep copy 
print(arr2)
arr2[2]=200
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[  1   2 100   4   5   6   7   8   9  10  11  12]
[  1   2 100   4   5   6   7   8   9  10  11  12]
[  1   2 200   4   5   6   7   8   9  10  11  12]


In [28]:
m=np.ones(3)
print(m)
add_arr=[10,20,30]
print(add_arr)

print(m+add_arr)

[1. 1. 1.]
[10, 20, 30]
[11. 21. 31.]


In [ ]:
table=np.arange(1,101).reshape(10,10)

print(table)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [34]:
arr=np.array([10,30,49,34,90,50,34,70])
arr1 = np.where(arr % 5 == 0, 0, arr)
print(arr1)

[ 0  0 49 34  0  0 34  0]


In [ ]:
arr=np.array([10,30,49,34,90,50,34,70])
